# Site settings
name: cyzlmh's blog
email: cyzlmh@gmail.com
author: cyzlmh
url: ""
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/cyzlmh/
baseurl: ""
description: An experimental blog
meta_description: 玩一玩
motto: 让我此生唯一自传，如同诗一般
banner: /

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:categories/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: cyzlmh

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

plugins:
  - jekyll-paginate
